POST http://localhost:3001/api/books/
content-type: application/json

{
    "title": "Harry Potter and the Philosopher's Stone",
    "author": ["J. K. Rowling"],
    "year": "1997",
    "genres": ["Fiction"],
    "status": "Read"
}

######

GET http://localhost:3001/api/books/